env_name: Hanoi
detector: HanoiDetector
planning_mode: 0
planning_predicates: ['on', 'clear', 'grasped']

pddl_path: planning/PDDL/hanoi/
yolo_model: models/yolo/hanoi_yolo.pt
regressor_model: models/regressors/hanoi_regressor.pkl

policies:
  grasp: diffusion_policy/data/train_gt/grasp/checkpoints/save/epoch=1300-train_loss=0.011.ckpt
  drop: diffusion_policy/data/train_gt/drop/checkpoints/latest.ckpt
  reach_pick: diffusion_policy/data/train_gt/reach_pick/checkpoints/epoch=2550-train_loss=0.010.ckpt
  reach_place: diffusion_policy/data/train_gt/reach_place/checkpoints/latest.ckpt

object_mapping:
  cube1: o1
  cube2: o2
  cube3: o3
  peg1: o4
  peg2: o5
  peg3: o6

executors:
  - id: ReachPick
    policy_key: reach_pick
    termination_condition: reach_pick
    nulified_action_indexes: [3]
    oracle: true
    horizon_formula: "(8/n_act)*130"

  - id: Pick
    policy_key: grasp
    termination_condition: pick
    nulified_action_indexes: [0, 1]
    oracle: true
    horizon_formula: "(8/n_act)*60"

  - id: ReachDrop
    policy_key: reach_place
    termination_condition: reach_drop
    nulified_action_indexes: [3]
    oracle: true
    horizon_formula: "(8/n_act)*160"

  - id: Drop
    policy_key: drop
    termination_condition: drop
    nulified_action_indexes: [0, 1]
    oracle: true
    horizon_formula: "(8/n_act)*60"

goal_strategy: default   # use PDDL goal as-is