env_name: Hanoi
detector: HanoiDetector
planning_mode: 0
planning_predicates: ['on', 'clear', 'grasped']

pddl_path: planning/PDDL/hanoi/
yolo_model: models/yolo/hanoi_yolo.pt
regressor_model: models/regressors/hanoi_regressor.pkl

policies:
  grasp: models/policies/gt/grasp.ckpt
  drop: models/policies/gt/drop.ckpt
  reach_pick: models/policies/gt/reach_pick.ckpt
  reach_place: models/policies/gt/reach_place.ckpt

object_mapping:
  cube1: o1
  cube2: o2
  cube3: o3
  peg1: o4
  peg2: o5
  peg3: o6

executors:
  - id: ReachPick
    policy_key: reach_pick
    termination_condition: reach_pick
    nulified_action_indexes: [3]
    oracle: true
    horizon_formula: "(8/n_act)*50"

  - id: Pick
    policy_key: grasp
    termination_condition: pick
    nulified_action_indexes: [0, 1]
    oracle: true
    horizon_formula: "(8/n_act)*30"

  - id: ReachDrop
    policy_key: reach_place
    termination_condition: reach_drop
    nulified_action_indexes: [3]
    oracle: true
    horizon_formula: "(8/n_act)*50"

  - id: Drop
    policy_key: drop
    termination_condition: drop
    nulified_action_indexes: [0, 1]
    oracle: true
    horizon_formula: "(8/n_act)*30"

goal_strategy: default   # use PDDL goal as-is